name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Build error_set
      run: cd error_set && cargo build --verbose
    - name: Build err_trail
      run: cd err_trail && cargo build --verbose
    - name: Run std tests error_set
      run: cd error_set && cargo test --verbose --tests
    - name: Run error_set no_std tests
      run: rustup target add x86_64-unknown-linux-gnu && cd error_set/test_no_std && cargo run
    - name: Run error_set feature flags tests
      run: cd error_set && cargo test --tests --features tracing && cargo test --tests --features log
    - name: Run err_trail feature flags tests
      run: cd err_trail && cargo test --tests --features tracing && cargo test --tests --features log
