name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run std tests
      run: cargo test --verbose --tests
    - name: Run no_std tests
      run: rustup target add x86_64-unknown-linux-gnu && cd test_no_std && cargo run
    - name: Run feature flags tests
      run: cargo test --tests --features coerce_macro && cargo test --tests --features tracing && cargo test --tests --features log
